spring:
  datasource:
    url: jdbc:mysql://localhost:3306/jtest
    username: root
    password: guoguo841268
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: mysql
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        generate_statistics: false